//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtDestek.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GENMOT_MESSEntities1 : DbContext
    {
        public GENMOT_MESSEntities1()
            : base("name=GENMOT_MESSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Birim> Tbl_Birim { get; set; }
        public virtual DbSet<Tbl_Destek> Tbl_Destek { get; set; }
        public virtual DbSet<Tbl_Personel> Tbl_Personel { get; set; }
    }
}
