//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtDestek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Destek
    {
        public int ID { get; set; }
        public Nullable<int> AdSoyad { get; set; }
        public Nullable<byte> Birim { get; set; }
        public string Aciklama { get; set; }
        public string Durum { get; set; }
        public string TalepOnaylayan { get; set; }
        public string TalepSorunAciklama { get; set; }
        public Nullable<bool> OkunduMu { get; set; }
        public Nullable<System.DateTime> TalepTarih { get; set; }
        public Nullable<System.DateTime> OnayTarih { get; set; }
        public Nullable<System.DateTime> BitisTarih { get; set; }
        public Nullable<System.DateTime> RedTarih { get; set; }
        public Nullable<System.DateTime> BeklemeTarih { get; set; }
    
        public virtual Tbl_Birim Tbl_Birim { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
    }
}
